/**
 * Frozen GET https://discord.com/api/v10/guilds/templates/hgM48av5Q69A
 * captured 2026-08-25. Unauthenticated. Do not refresh unless the mapper
 * contract changes; the test is that this snapshot still maps the same way.
 */
export const FRIENDS_FAMILY_TEMPLATE = {
  code: "hgM48av5Q69A",
  name: "Friends & Family",
  updated_at: "2020-05-01T17:57:38+00:00",
  is_dirty: null,
  serialized_source_guild: {
    name: "Friends & Family",
    icon_hash: null,
    roles: [
      {
        id: 0,
        name: "@everyone",
        permissions: "2248329584434769",
        color: 0,
        hoist: false,
        mentionable: false,
      },
    ],
    channels: [
      {
        id: 1,
        type: 4,
        name: "Text Channels",
        position: 1,
        topic: null,
        parent_id: null,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 2,
        type: 0,
        name: "general",
        position: 1,
        topic: null,
        parent_id: 1,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 3,
        type: 0,
        name: "games",
        position: 2,
        topic: null,
        parent_id: 1,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 4,
        type: 0,
        name: "music",
        position: 5,
        topic: null,
        parent_id: 1,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 5,
        type: 4,
        name: "Voice Channels",
        position: 2,
        topic: null,
        parent_id: null,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 6,
        type: 2,
        name: "Lounge",
        position: 0,
        topic: null,
        parent_id: 5,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
      {
        id: 7,
        type: 2,
        name: "Stream Room",
        position: 1,
        topic: null,
        parent_id: 5,
        nsfw: false,
        rate_limit_per_user: 0,
        bitrate: 64000,
        permission_overwrites: [],
        available_tags: [],
      },
    ],
  },
} as const;
