#!/usr/bin/env bash
# Generates fresh, harness-only credentials every run and writes them to
# .data/ (gitignored, never committed): a LiveKit API key/secret pair, the
# pqp-remux control-plane HMAC secret, and the media-origin key. Renders
# .data/livekit.yaml from livekit.yaml.tmpl with the LiveKit pair baked in.
#
# NO PRODUCTION KEY EVER TOUCHES THIS SCRIPT. It does not read
# LIVEKIT_API_KEY/SECRET or REMUX_CONTROL_SECRET from the operator's shell
# on purpose -- see README.md "Ephemeral keys, not production ones".
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
mkdir -p .data

rand_hex() { openssl rand -hex "$1"; }

LIVEKIT_API_KEY="harness$(rand_hex 6)"
LIVEKIT_API_SECRET="$(rand_hex 32)"
REMUX_CONTROL_SECRET="$(rand_hex 32)"
MEDIA_ORIGIN_KEY="$(rand_hex 32)"

cat > .data/harness.env <<EOF
# Generated by scripts/gen-keys.sh at $(date -u +%FT%TZ). Ephemeral,
# harness-only. Never a production credential. Do not commit.
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
REMUX_CONTROL_SECRET=${REMUX_CONTROL_SECRET}
MEDIA_ORIGIN_KEY=${MEDIA_ORIGIN_KEY}
EOF

sed -e "s/__LIVEKIT_API_KEY__/${LIVEKIT_API_KEY}/" \
    -e "s/__LIVEKIT_API_SECRET__/${LIVEKIT_API_SECRET}/" \
    livekit.yaml.tmpl > .data/livekit.yaml

echo "gen-keys: wrote .data/harness.env and .data/livekit.yaml (ephemeral, gitignored)"
